// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: internal/games/poker/pb/poker.proto

package pokerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stage is the current point in a Texas Hold'em hand.
type Stage int32

const (
	Stage_STAGE_UNSPECIFIED Stage = 0
	Stage_STAGE_PREFLOP     Stage = 1
	Stage_STAGE_FLOP        Stage = 2
	Stage_STAGE_TURN        Stage = 3
	Stage_STAGE_RIVER       Stage = 4
	Stage_STAGE_SHOWDOWN    Stage = 5
	Stage_STAGE_HAND_OVER   Stage = 6
)

// Enum value maps for Stage.
var (
	Stage_name = map[int32]string{
		0: "STAGE_UNSPECIFIED",
		1: "STAGE_PREFLOP",
		2: "STAGE_FLOP",
		3: "STAGE_TURN",
		4: "STAGE_RIVER",
		5: "STAGE_SHOWDOWN",
		6: "STAGE_HAND_OVER",
	}
	Stage_value = map[string]int32{
		"STAGE_UNSPECIFIED": 0,
		"STAGE_PREFLOP":     1,
		"STAGE_FLOP":        2,
		"STAGE_TURN":        3,
		"STAGE_RIVER":       4,
		"STAGE_SHOWDOWN":    5,
		"STAGE_HAND_OVER":   6,
	}
)

func (x Stage) Enum() *Stage {
	p := new(Stage)
	*p = x
	return p
}

func (x Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_games_poker_pb_poker_proto_enumTypes[0].Descriptor()
}

func (Stage) Type() protoreflect.EnumType {
	return &file_internal_games_poker_pb_poker_proto_enumTypes[0]
}

func (x Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stage.Descriptor instead.
func (Stage) EnumDescriptor() ([]byte, []int) {
	return file_internal_games_poker_pb_poker_proto_rawDescGZIP(), []int{0}
}

// SeatStatus is a player's participation in the current hand.
type SeatStatus int32

const (
	SeatStatus_SEAT_STATUS_UNSPECIFIED SeatStatus = 0
	SeatStatus_SEAT_STATUS_ACTIVE      SeatStatus = 1 // still in the hand and able to act
	SeatStatus_SEAT_STATUS_FOLDED      SeatStatus = 2
	SeatStatus_SEAT_STATUS_ALLIN       SeatStatus = 3 // committed entire stack, cannot act further
	SeatStatus_SEAT_STATUS_SITTING_OUT SeatStatus = 4 // no chips / waiting for next hand
)

// Enum value maps for SeatStatus.
var (
	SeatStatus_name = map[int32]string{
		0: "SEAT_STATUS_UNSPECIFIED",
		1: "SEAT_STATUS_ACTIVE",
		2: "SEAT_STATUS_FOLDED",
		3: "SEAT_STATUS_ALLIN",
		4: "SEAT_STATUS_SITTING_OUT",
	}
	SeatStatus_value = map[string]int32{
		"SEAT_STATUS_UNSPECIFIED": 0,
		"SEAT_STATUS_ACTIVE":      1,
		"SEAT_STATUS_FOLDED":      2,
		"SEAT_STATUS_ALLIN":       3,
		"SEAT_STATUS_SITTING_OUT": 4,
	}
)

func (x SeatStatus) Enum() *SeatStatus {
	p := new(SeatStatus)
	*p = x
	return p
}

func (x SeatStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeatStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_games_poker_pb_poker_proto_enumTypes[1].Descriptor()
}

func (SeatStatus) Type() protoreflect.EnumType {
	return &file_internal_games_poker_pb_poker_proto_enumTypes[1]
}

func (x SeatStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeatStatus.Descriptor instead.
func (SeatStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_games_poker_pb_poker_proto_rawDescGZIP(), []int{1}
}

type Seat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SeatIndex      int32                  `protobuf:"varint,1,opt,name=seat_index,json=seatIndex,proto3" json:"seat_index,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Stack          int64                  `protobuf:"varint,3,opt,name=stack,proto3" json:"stack,omitempty"`                                         // chips behind (not yet in the pot)
	Committed      int64                  `protobuf:"varint,4,opt,name=committed,proto3" json:"committed,omitempty"`                                 // chips committed in the CURRENT betting round
	TotalCommitted int64                  `protobuf:"varint,5,opt,name=total_committed,json=totalCommitted,proto3" json:"total_committed,omitempty"` // chips committed over the whole hand (for side pots)
	HoleCards      []int32                `protobuf:"varint,6,rep,packed,name=hole_cards,json=holeCards,proto3" json:"hole_cards,omitempty"`
	Status         SeatStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=bgex.poker.v1.SeatStatus" json:"status,omitempty"`
	HasActed       bool                   `protobuf:"varint,8,opt,name=has_acted,json=hasActed,proto3" json:"has_acted,omitempty"` // acted since the last aggressive action this round
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_internal_games_poker_pb_poker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_games_poker_pb_poker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_internal_games_poker_pb_poker_proto_rawDescGZIP(), []int{0}
}

func (x *Seat) GetSeatIndex() int32 {
	if x != nil {
		return x.SeatIndex
	}
	return 0
}

func (x *Seat) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Seat) GetStack() int64 {
	if x != nil {
		return x.Stack
	}
	return 0
}

func (x *Seat) GetCommitted() int64 {
	if x != nil {
		return x.Committed
	}
	return 0
}

func (x *Seat) GetTotalCommitted() int64 {
	if x != nil {
		return x.TotalCommitted
	}
	return 0
}

func (x *Seat) GetHoleCards() []int32 {
	if x != nil {
		return x.HoleCards
	}
	return nil
}

func (x *Seat) GetStatus() SeatStatus {
	if x != nil {
		return x.Status
	}
	return SeatStatus_SEAT_STATUS_UNSPECIFIED
}

func (x *Seat) GetHasActed() bool {
	if x != nil {
		return x.HasActed
	}
	return false
}

type Pot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	EligibleSeats []int32                `protobuf:"varint,2,rep,packed,name=eligible_seats,json=eligibleSeats,proto3" json:"eligible_seats,omitempty"` // seat indices allowed to win this pot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pot) Reset() {
	*x = Pot{}
	mi := &file_internal_games_poker_pb_poker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pot) ProtoMessage() {}

func (x *Pot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_games_poker_pb_poker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pot.ProtoReflect.Descriptor instead.
func (*Pot) Descriptor() ([]byte, []int) {
	return file_internal_games_poker_pb_poker_proto_rawDescGZIP(), []int{1}
}

func (x *Pot) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Pot) GetEligibleSeats() []int32 {
	if x != nil {
		return x.EligibleSeats
	}
	return nil
}

type HandResult struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Payouts map[int32]int64        `protobuf:"bytes,1,rep,name=payouts,proto3" json:"payouts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // seat_index -> chips won
	Board   []int32                `protobuf:"varint,2,rep,packed,name=board,proto3" json:"board,omitempty"`
	// per-seat best-hand description shown at showdown; empty for fold wins.
	HandDescriptions map[int32]string `protobuf:"bytes,3,rep,name=hand_descriptions,json=handDescriptions,proto3" json:"hand_descriptions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ShownSeats       []int32          `protobuf:"varint,4,rep,packed,name=shown_seats,json=shownSeats,proto3" json:"shown_seats,omitempty"` // seats whose hole cards are revealed
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HandResult) Reset() {
	*x = HandResult{}
	mi := &file_internal_games_poker_pb_poker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandResult) ProtoMessage() {}

func (x *HandResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_games_poker_pb_poker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandResult.ProtoReflect.Descriptor instead.
func (*HandResult) Descriptor() ([]byte, []int) {
	return file_internal_games_poker_pb_poker_proto_rawDescGZIP(), []int{2}
}

func (x *HandResult) GetPayouts() map[int32]int64 {
	if x != nil {
		return x.Payouts
	}
	return nil
}

func (x *HandResult) GetBoard() []int32 {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *HandResult) GetHandDescriptions() map[int32]string {
	if x != nil {
		return x.HandDescriptions
	}
	return nil
}

func (x *HandResult) GetShownSeats() []int32 {
	if x != nil {
		return x.ShownSeats
	}
	return nil
}

type TableState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HandNo        int32                  `protobuf:"varint,1,opt,name=hand_no,json=handNo,proto3" json:"hand_no,omitempty"`
	Stage         Stage                  `protobuf:"varint,2,opt,name=stage,proto3,enum=bgex.poker.v1.Stage" json:"stage,omitempty"`
	Seats         []*Seat                `protobuf:"bytes,3,rep,name=seats,proto3" json:"seats,omitempty"`
	Deck          []int32                `protobuf:"varint,4,rep,packed,name=deck,proto3" json:"deck,omitempty"`                           // remaining deck; deal from the front
	Board         []int32                `protobuf:"varint,5,rep,packed,name=board,proto3" json:"board,omitempty"`                         // community cards
	Button        int32                  `protobuf:"varint,6,opt,name=button,proto3" json:"button,omitempty"`                              // seat index of the dealer button
	CurrentTurn   int32                  `protobuf:"varint,7,opt,name=current_turn,json=currentTurn,proto3" json:"current_turn,omitempty"` // seat index to act; -1 if none
	SmallBlind    int64                  `protobuf:"varint,8,opt,name=small_blind,json=smallBlind,proto3" json:"small_blind,omitempty"`
	BigBlind      int64                  `protobuf:"varint,9,opt,name=big_blind,json=bigBlind,proto3" json:"big_blind,omitempty"`
	CurrentBet    int64                  `protobuf:"varint,10,opt,name=current_bet,json=currentBet,proto3" json:"current_bet,omitempty"`          // highest per-player commitment this round
	MinRaise      int64                  `protobuf:"varint,11,opt,name=min_raise,json=minRaise,proto3" json:"min_raise,omitempty"`                // minimum legal raise increment
	LastAggressor int32                  `protobuf:"varint,12,opt,name=last_aggressor,json=lastAggressor,proto3" json:"last_aggressor,omitempty"` // seat index of last bet/raise; -1 if none
	Pots          []*Pot                 `protobuf:"bytes,13,rep,name=pots,proto3" json:"pots,omitempty"`                                         // computed at showdown
	Result        *HandResult            `protobuf:"bytes,14,opt,name=result,proto3" json:"result,omitempty"`                                     // populated once stage == STAGE_HAND_OVER
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableState) Reset() {
	*x = TableState{}
	mi := &file_internal_games_poker_pb_poker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableState) ProtoMessage() {}

func (x *TableState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_games_poker_pb_poker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableState.ProtoReflect.Descriptor instead.
func (*TableState) Descriptor() ([]byte, []int) {
	return file_internal_games_poker_pb_poker_proto_rawDescGZIP(), []int{3}
}

func (x *TableState) GetHandNo() int32 {
	if x != nil {
		return x.HandNo
	}
	return 0
}

func (x *TableState) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_STAGE_UNSPECIFIED
}

func (x *TableState) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

func (x *TableState) GetDeck() []int32 {
	if x != nil {
		return x.Deck
	}
	return nil
}

func (x *TableState) GetBoard() []int32 {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *TableState) GetButton() int32 {
	if x != nil {
		return x.Button
	}
	return 0
}

func (x *TableState) GetCurrentTurn() int32 {
	if x != nil {
		return x.CurrentTurn
	}
	return 0
}

func (x *TableState) GetSmallBlind() int64 {
	if x != nil {
		return x.SmallBlind
	}
	return 0
}

func (x *TableState) GetBigBlind() int64 {
	if x != nil {
		return x.BigBlind
	}
	return 0
}

func (x *TableState) GetCurrentBet() int64 {
	if x != nil {
		return x.CurrentBet
	}
	return 0
}

func (x *TableState) GetMinRaise() int64 {
	if x != nil {
		return x.MinRaise
	}
	return 0
}

func (x *TableState) GetLastAggressor() int32 {
	if x != nil {
		return x.LastAggressor
	}
	return 0
}

func (x *TableState) GetPots() []*Pot {
	if x != nil {
		return x.Pots
	}
	return nil
}

func (x *TableState) GetResult() *HandResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_internal_games_poker_pb_poker_proto protoreflect.FileDescriptor

const file_internal_games_poker_pb_poker_proto_rawDesc = "" +
	"\n" +
	"#internal/games/poker/pb/poker.proto\x12\rbgex.poker.v1\"\x8a\x02\n" +
	"\x04Seat\x12\x1d\n" +
	"\n" +
	"seat_index\x18\x01 \x01(\x05R\tseatIndex\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05stack\x18\x03 \x01(\x03R\x05stack\x12\x1c\n" +
	"\tcommitted\x18\x04 \x01(\x03R\tcommitted\x12'\n" +
	"\x0ftotal_committed\x18\x05 \x01(\x03R\x0etotalCommitted\x12\x1d\n" +
	"\n" +
	"hole_cards\x18\x06 \x03(\x05R\tholeCards\x121\n" +
	"\x06status\x18\a \x01(\x0e2\x19.bgex.poker.v1.SeatStatusR\x06status\x12\x1b\n" +
	"\thas_acted\x18\b \x01(\bR\bhasActed\"D\n" +
	"\x03Pot\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12%\n" +
	"\x0eeligible_seats\x18\x02 \x03(\x05R\religibleSeats\"\xe4\x02\n" +
	"\n" +
	"HandResult\x12@\n" +
	"\apayouts\x18\x01 \x03(\v2&.bgex.poker.v1.HandResult.PayoutsEntryR\apayouts\x12\x14\n" +
	"\x05board\x18\x02 \x03(\x05R\x05board\x12\\\n" +
	"\x11hand_descriptions\x18\x03 \x03(\v2/.bgex.poker.v1.HandResult.HandDescriptionsEntryR\x10handDescriptions\x12\x1f\n" +
	"\vshown_seats\x18\x04 \x03(\x05R\n" +
	"shownSeats\x1a:\n" +
	"\fPayoutsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aC\n" +
	"\x15HandDescriptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdf\x03\n" +
	"\n" +
	"TableState\x12\x17\n" +
	"\ahand_no\x18\x01 \x01(\x05R\x06handNo\x12*\n" +
	"\x05stage\x18\x02 \x01(\x0e2\x14.bgex.poker.v1.StageR\x05stage\x12)\n" +
	"\x05seats\x18\x03 \x03(\v2\x13.bgex.poker.v1.SeatR\x05seats\x12\x12\n" +
	"\x04deck\x18\x04 \x03(\x05R\x04deck\x12\x14\n" +
	"\x05board\x18\x05 \x03(\x05R\x05board\x12\x16\n" +
	"\x06button\x18\x06 \x01(\x05R\x06button\x12!\n" +
	"\fcurrent_turn\x18\a \x01(\x05R\vcurrentTurn\x12\x1f\n" +
	"\vsmall_blind\x18\b \x01(\x03R\n" +
	"smallBlind\x12\x1b\n" +
	"\tbig_blind\x18\t \x01(\x03R\bbigBlind\x12\x1f\n" +
	"\vcurrent_bet\x18\n" +
	" \x01(\x03R\n" +
	"currentBet\x12\x1b\n" +
	"\tmin_raise\x18\v \x01(\x03R\bminRaise\x12%\n" +
	"\x0elast_aggressor\x18\f \x01(\x05R\rlastAggressor\x12&\n" +
	"\x04pots\x18\r \x03(\v2\x12.bgex.poker.v1.PotR\x04pots\x121\n" +
	"\x06result\x18\x0e \x01(\v2\x19.bgex.poker.v1.HandResultR\x06result*\x8b\x01\n" +
	"\x05Stage\x12\x15\n" +
	"\x11STAGE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTAGE_PREFLOP\x10\x01\x12\x0e\n" +
	"\n" +
	"STAGE_FLOP\x10\x02\x12\x0e\n" +
	"\n" +
	"STAGE_TURN\x10\x03\x12\x0f\n" +
	"\vSTAGE_RIVER\x10\x04\x12\x12\n" +
	"\x0eSTAGE_SHOWDOWN\x10\x05\x12\x13\n" +
	"\x0fSTAGE_HAND_OVER\x10\x06*\x8d\x01\n" +
	"\n" +
	"SeatStatus\x12\x1b\n" +
	"\x17SEAT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SEAT_STATUS_ACTIVE\x10\x01\x12\x16\n" +
	"\x12SEAT_STATUS_FOLDED\x10\x02\x12\x15\n" +
	"\x11SEAT_STATUS_ALLIN\x10\x03\x12\x1b\n" +
	"\x17SEAT_STATUS_SITTING_OUT\x10\x04BDZBgithub.com/serediukit/bgex-backend/internal/games/poker/pb;pokerpbb\x06proto3"

var (
	file_internal_games_poker_pb_poker_proto_rawDescOnce sync.Once
	file_internal_games_poker_pb_poker_proto_rawDescData []byte
)

func file_internal_games_poker_pb_poker_proto_rawDescGZIP() []byte {
	file_internal_games_poker_pb_poker_proto_rawDescOnce.Do(func() {
		file_internal_games_poker_pb_poker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_games_poker_pb_poker_proto_rawDesc), len(file_internal_games_poker_pb_poker_proto_rawDesc)))
	})
	return file_internal_games_poker_pb_poker_proto_rawDescData
}

var file_internal_games_poker_pb_poker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_games_poker_pb_poker_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_games_poker_pb_poker_proto_goTypes = []any{
	(Stage)(0),         // 0: bgex.poker.v1.Stage
	(SeatStatus)(0),    // 1: bgex.poker.v1.SeatStatus
	(*Seat)(nil),       // 2: bgex.poker.v1.Seat
	(*Pot)(nil),        // 3: bgex.poker.v1.Pot
	(*HandResult)(nil), // 4: bgex.poker.v1.HandResult
	(*TableState)(nil), // 5: bgex.poker.v1.TableState
	nil,                // 6: bgex.poker.v1.HandResult.PayoutsEntry
	nil,                // 7: bgex.poker.v1.HandResult.HandDescriptionsEntry
}
var file_internal_games_poker_pb_poker_proto_depIdxs = []int32{
	1, // 0: bgex.poker.v1.Seat.status:type_name -> bgex.poker.v1.SeatStatus
	6, // 1: bgex.poker.v1.HandResult.payouts:type_name -> bgex.poker.v1.HandResult.PayoutsEntry
	7, // 2: bgex.poker.v1.HandResult.hand_descriptions:type_name -> bgex.poker.v1.HandResult.HandDescriptionsEntry
	0, // 3: bgex.poker.v1.TableState.stage:type_name -> bgex.poker.v1.Stage
	2, // 4: bgex.poker.v1.TableState.seats:type_name -> bgex.poker.v1.Seat
	3, // 5: bgex.poker.v1.TableState.pots:type_name -> bgex.poker.v1.Pot
	4, // 6: bgex.poker.v1.TableState.result:type_name -> bgex.poker.v1.HandResult
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_internal_games_poker_pb_poker_proto_init() }
func file_internal_games_poker_pb_poker_proto_init() {
	if File_internal_games_poker_pb_poker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_games_poker_pb_poker_proto_rawDesc), len(file_internal_games_poker_pb_poker_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_games_poker_pb_poker_proto_goTypes,
		DependencyIndexes: file_internal_games_poker_pb_poker_proto_depIdxs,
		EnumInfos:         file_internal_games_poker_pb_poker_proto_enumTypes,
		MessageInfos:      file_internal_games_poker_pb_poker_proto_msgTypes,
	}.Build()
	File_internal_games_poker_pb_poker_proto = out.File
	file_internal_games_poker_pb_poker_proto_goTypes = nil
	file_internal_games_poker_pb_poker_proto_depIdxs = nil
}
