// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: internal/games/ttr/pb/ttr.proto

package ttrpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Color is a train-card colour or a route colour. GRAY is route-only, LOCO is
// card-only (rules §3.3).
type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_COLOR_PURPLE      Color = 1
	Color_COLOR_BLUE        Color = 2
	Color_COLOR_ORANGE      Color = 3
	Color_COLOR_WHITE       Color = 4
	Color_COLOR_GREEN       Color = 5
	Color_COLOR_YELLOW      Color = 6
	Color_COLOR_BLACK       Color = 7
	Color_COLOR_RED         Color = 8
	Color_COLOR_GRAY        Color = 9
	Color_COLOR_LOCO        Color = 10
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0:  "COLOR_UNSPECIFIED",
		1:  "COLOR_PURPLE",
		2:  "COLOR_BLUE",
		3:  "COLOR_ORANGE",
		4:  "COLOR_WHITE",
		5:  "COLOR_GREEN",
		6:  "COLOR_YELLOW",
		7:  "COLOR_BLACK",
		8:  "COLOR_RED",
		9:  "COLOR_GRAY",
		10: "COLOR_LOCO",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"COLOR_PURPLE":      1,
		"COLOR_BLUE":        2,
		"COLOR_ORANGE":      3,
		"COLOR_WHITE":       4,
		"COLOR_GREEN":       5,
		"COLOR_YELLOW":      6,
		"COLOR_BLACK":       7,
		"COLOR_RED":         8,
		"COLOR_GRAY":        9,
		"COLOR_LOCO":        10,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_games_ttr_pb_ttr_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_internal_games_ttr_pb_ttr_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_internal_games_ttr_pb_ttr_proto_rawDescGZIP(), []int{0}
}

// Phase drives the state machine. AWAITING_* phases are pending decisions
// (plan Q9); NORMAL means the current player picks one of the four actions.
type Phase int32

const (
	Phase_PHASE_UNSPECIFIED          Phase = 0
	Phase_PHASE_SETUP_TICKETS        Phase = 1 // §5.7 simultaneous keep, min 2
	Phase_PHASE_NORMAL               Phase = 2 // §6
	Phase_PHASE_AWAITING_SECOND_DRAW Phase = 3 // §7.1 mid-draw, one card taken
	Phase_PHASE_AWAITING_TUNNEL      Phase = 4 // §8.4 surcharge decision
	Phase_PHASE_AWAITING_TICKET_KEEP Phase = 5 // §9 keep >= 1
	Phase_PHASE_SCORING              Phase = 6
	Phase_PHASE_FINISHED             Phase = 7
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_SETUP_TICKETS",
		2: "PHASE_NORMAL",
		3: "PHASE_AWAITING_SECOND_DRAW",
		4: "PHASE_AWAITING_TUNNEL",
		5: "PHASE_AWAITING_TICKET_KEEP",
		6: "PHASE_SCORING",
		7: "PHASE_FINISHED",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED":          0,
		"PHASE_SETUP_TICKETS":        1,
		"PHASE_NORMAL":               2,
		"PHASE_AWAITING_SECOND_DRAW": 3,
		"PHASE_AWAITING_TUNNEL":      4,
		"PHASE_AWAITING_TICKET_KEEP": 5,
		"PHASE_SCORING":              6,
		"PHASE_FINISHED":             7,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_games_ttr_pb_ttr_proto_enumTypes[1].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_internal_games_ttr_pb_ttr_proto_enumTypes[1]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_internal_games_ttr_pb_ttr_proto_rawDescGZIP(), []int{1}
}

type PlayerState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SeatIndex        int32                  `protobuf:"varint,1,opt,name=seat_index,json=seatIndex,proto3" json:"seat_index,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Hand             map[int32]int32        `protobuf:"bytes,3,rep,name=hand,proto3" json:"hand,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Color(int) -> count, includes COLOR_LOCO
	TicketIds        []int32                `protobuf:"varint,4,rep,packed,name=ticket_ids,json=ticketIds,proto3" json:"ticket_ids,omitempty"`                                          // secret
	TrainsLeft       int32                  `protobuf:"varint,5,opt,name=trains_left,json=trainsLeft,proto3" json:"trains_left,omitempty"`                                              // starts 45 (§3.1)
	StationsLeft     int32                  `protobuf:"varint,6,opt,name=stations_left,json=stationsLeft,proto3" json:"stations_left,omitempty"`                                        // starts 3
	RouteScore       int32                  `protobuf:"varint,7,opt,name=route_score,json=routeScore,proto3" json:"route_score,omitempty"`                                              // running, routes only (§13.1)
	ClaimedRouteIds  []int32                `protobuf:"varint,8,rep,packed,name=claimed_route_ids,json=claimedRouteIds,proto3" json:"claimed_route_ids,omitempty"`
	StationCities    []string               `protobuf:"bytes,9,rep,name=station_cities,json=stationCities,proto3" json:"station_cities,omitempty"`
	Resigned         bool                   `protobuf:"varint,10,opt,name=resigned,proto3" json:"resigned,omitempty"`                                                  // plan Q14
	SetupTicketOffer []int32                `protobuf:"varint,11,rep,packed,name=setup_ticket_offer,json=setupTicketOffer,proto3" json:"setup_ticket_offer,omitempty"` // §5 dealt 4, cleared after keep
	SetupDone        bool                   `protobuf:"varint,12,opt,name=setup_done,json=setupDone,proto3" json:"setup_done,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_internal_games_ttr_pb_ttr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_games_ttr_pb_ttr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_internal_games_ttr_pb_ttr_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerState) GetSeatIndex() int32 {
	if x != nil {
		return x.SeatIndex
	}
	return 0
}

func (x *PlayerState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerState) GetHand() map[int32]int32 {
	if x != nil {
		return x.Hand
	}
	return nil
}

func (x *PlayerState) GetTicketIds() []int32 {
	if x != nil {
		return x.TicketIds
	}
	return nil
}

func (x *PlayerState) GetTrainsLeft() int32 {
	if x != nil {
		return x.TrainsLeft
	}
	return 0
}

func (x *PlayerState) GetStationsLeft() int32 {
	if x != nil {
		return x.StationsLeft
	}
	return 0
}

func (x *PlayerState) GetRouteScore() int32 {
	if x != nil {
		return x.RouteScore
	}
	return 0
}

func (x *PlayerState) GetClaimedRouteIds() []int32 {
	if x != nil {
		return x.ClaimedRouteIds
	}
	return nil
}

func (x *PlayerState) GetStationCities() []string {
	if x != nil {
		return x.StationCities
	}
	return nil
}

func (x *PlayerState) GetResigned() bool {
	if x != nil {
		return x.Resigned
	}
	return false
}

func (x *PlayerState) GetSetupTicketOffer() []int32 {
	if x != nil {
		return x.SetupTicketOffer
	}
	return nil
}

func (x *PlayerState) GetSetupDone() bool {
	if x != nil {
		return x.SetupDone
	}
	return false
}

// PendingTunnel holds a committed base payment awaiting the §8.4 surcharge
// decision. Revealed cards are NOT shown to other players until resolution.
type PendingTunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       int32                  `protobuf:"varint,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	BasePayment   map[int32]int32        `protobuf:"bytes,2,rep,name=base_payment,json=basePayment,proto3" json:"base_payment,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Color -> count actually spent
	PaymentColor  Color                  `protobuf:"varint,3,opt,name=payment_color,json=paymentColor,proto3,enum=bgex.ttr.v1.Color" json:"payment_color,omitempty"`                                                  // non-loco colour used, or COLOR_LOCO
	Revealed      []int32                `protobuf:"varint,4,rep,packed,name=revealed,proto3" json:"revealed,omitempty"`                                                                                              // Color values, 0..3 cards
	Surcharge     int32                  `protobuf:"varint,5,opt,name=surcharge,proto3" json:"surcharge,omitempty"`                                                                                                   // number of extra cards required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingTunnel) Reset() {
	*x = PendingTunnel{}
	mi := &file_internal_games_ttr_pb_ttr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingTunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingTunnel) ProtoMessage() {}

func (x *PendingTunnel) ProtoReflect() protoreflect.Message {
	mi := &file_internal_games_ttr_pb_ttr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingTunnel.ProtoReflect.Descriptor instead.
func (*PendingTunnel) Descriptor() ([]byte, []int) {
	return file_internal_games_ttr_pb_ttr_proto_rawDescGZIP(), []int{1}
}

func (x *PendingTunnel) GetRouteId() int32 {
	if x != nil {
		return x.RouteId
	}
	return 0
}

func (x *PendingTunnel) GetBasePayment() map[int32]int32 {
	if x != nil {
		return x.BasePayment
	}
	return nil
}

func (x *PendingTunnel) GetPaymentColor() Color {
	if x != nil {
		return x.PaymentColor
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *PendingTunnel) GetRevealed() []int32 {
	if x != nil {
		return x.Revealed
	}
	return nil
}

func (x *PendingTunnel) GetSurcharge() int32 {
	if x != nil {
		return x.Surcharge
	}
	return 0
}

// PendingTicketDraw holds the 3 drawn tickets awaiting a §9 keep decision.
type PendingTicketDraw struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OfferedTicketIds []int32                `protobuf:"varint,1,rep,packed,name=offered_ticket_ids,json=offeredTicketIds,proto3" json:"offered_ticket_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PendingTicketDraw) Reset() {
	*x = PendingTicketDraw{}
	mi := &file_internal_games_ttr_pb_ttr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingTicketDraw) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingTicketDraw) ProtoMessage() {}

func (x *PendingTicketDraw) ProtoReflect() protoreflect.Message {
	mi := &file_internal_games_ttr_pb_ttr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingTicketDraw.ProtoReflect.Descriptor instead.
func (*PendingTicketDraw) Descriptor() ([]byte, []int) {
	return file_internal_games_ttr_pb_ttr_proto_rawDescGZIP(), []int{2}
}

func (x *PendingTicketDraw) GetOfferedTicketIds() []int32 {
	if x != nil {
		return x.OfferedTicketIds
	}
	return nil
}

type DrawProgress struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CardsTaken       int32                  `protobuf:"varint,1,opt,name=cards_taken,json=cardsTaken,proto3" json:"cards_taken,omitempty"`                       // 0..2 this turn
	FaceUpLocoLocked bool                   `protobuf:"varint,2,opt,name=face_up_loco_locked,json=faceUpLocoLocked,proto3" json:"face_up_loco_locked,omitempty"` // §7.2 after first card is taken
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DrawProgress) Reset() {
	*x = DrawProgress{}
	mi := &file_internal_games_ttr_pb_ttr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawProgress) ProtoMessage() {}

func (x *DrawProgress) ProtoReflect() protoreflect.Message {
	mi := &file_internal_games_ttr_pb_ttr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawProgress.ProtoReflect.Descriptor instead.
func (*DrawProgress) Descriptor() ([]byte, []int) {
	return file_internal_games_ttr_pb_ttr_proto_rawDescGZIP(), []int{3}
}

func (x *DrawProgress) GetCardsTaken() int32 {
	if x != nil {
		return x.CardsTaken
	}
	return 0
}

func (x *DrawProgress) GetFaceUpLocoLocked() bool {
	if x != nil {
		return x.FaceUpLocoLocked
	}
	return false
}

type ScoreBreakdown struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SeatIndex              int32                  `protobuf:"varint,1,opt,name=seat_index,json=seatIndex,proto3" json:"seat_index,omitempty"`
	RoutePoints            int32                  `protobuf:"varint,2,opt,name=route_points,json=routePoints,proto3" json:"route_points,omitempty"`
	TicketsCompletedPoints int32                  `protobuf:"varint,3,opt,name=tickets_completed_points,json=ticketsCompletedPoints,proto3" json:"tickets_completed_points,omitempty"`
	TicketsMissedPoints    int32                  `protobuf:"varint,4,opt,name=tickets_missed_points,json=ticketsMissedPoints,proto3" json:"tickets_missed_points,omitempty"` // positive magnitude, subtracted
	StationBonus           int32                  `protobuf:"varint,5,opt,name=station_bonus,json=stationBonus,proto3" json:"station_bonus,omitempty"`                        // 4 * unbuilt (§13.5)
	LongestPathBonus       int32                  `protobuf:"varint,6,opt,name=longest_path_bonus,json=longestPathBonus,proto3" json:"longest_path_bonus,omitempty"`          // 10 or 0 (§13.3)
	LongestPathLength      int32                  `protobuf:"varint,7,opt,name=longest_path_length,json=longestPathLength,proto3" json:"longest_path_length,omitempty"`
	Total                  int32                  `protobuf:"varint,8,opt,name=total,proto3" json:"total,omitempty"`
	Rank                   int32                  `protobuf:"varint,9,opt,name=rank,proto3" json:"rank,omitempty"`
	CompletedTicketIds     []int32                `protobuf:"varint,10,rep,packed,name=completed_ticket_ids,json=completedTicketIds,proto3" json:"completed_ticket_ids,omitempty"`
	MissedTicketIds        []int32                `protobuf:"varint,11,rep,packed,name=missed_ticket_ids,json=missedTicketIds,proto3" json:"missed_ticket_ids,omitempty"`
	// station city -> borrowed opponent route id chosen by the optimizer (§13.4)
	BorrowedRoutes map[string]int32 `protobuf:"bytes,12,rep,name=borrowed_routes,json=borrowedRoutes,proto3" json:"borrowed_routes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SharedVictory  bool             `protobuf:"varint,13,opt,name=shared_victory,json=sharedVictory,proto3" json:"shared_victory,omitempty"` // §13.6.5
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScoreBreakdown) Reset() {
	*x = ScoreBreakdown{}
	mi := &file_internal_games_ttr_pb_ttr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreBreakdown) ProtoMessage() {}

func (x *ScoreBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_internal_games_ttr_pb_ttr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreBreakdown.ProtoReflect.Descriptor instead.
func (*ScoreBreakdown) Descriptor() ([]byte, []int) {
	return file_internal_games_ttr_pb_ttr_proto_rawDescGZIP(), []int{4}
}

func (x *ScoreBreakdown) GetSeatIndex() int32 {
	if x != nil {
		return x.SeatIndex
	}
	return 0
}

func (x *ScoreBreakdown) GetRoutePoints() int32 {
	if x != nil {
		return x.RoutePoints
	}
	return 0
}

func (x *ScoreBreakdown) GetTicketsCompletedPoints() int32 {
	if x != nil {
		return x.TicketsCompletedPoints
	}
	return 0
}

func (x *ScoreBreakdown) GetTicketsMissedPoints() int32 {
	if x != nil {
		return x.TicketsMissedPoints
	}
	return 0
}

func (x *ScoreBreakdown) GetStationBonus() int32 {
	if x != nil {
		return x.StationBonus
	}
	return 0
}

func (x *ScoreBreakdown) GetLongestPathBonus() int32 {
	if x != nil {
		return x.LongestPathBonus
	}
	return 0
}

func (x *ScoreBreakdown) GetLongestPathLength() int32 {
	if x != nil {
		return x.LongestPathLength
	}
	return 0
}

func (x *ScoreBreakdown) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ScoreBreakdown) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *ScoreBreakdown) GetCompletedTicketIds() []int32 {
	if x != nil {
		return x.CompletedTicketIds
	}
	return nil
}

func (x *ScoreBreakdown) GetMissedTicketIds() []int32 {
	if x != nil {
		return x.MissedTicketIds
	}
	return nil
}

func (x *ScoreBreakdown) GetBorrowedRoutes() map[string]int32 {
	if x != nil {
		return x.BorrowedRoutes
	}
	return nil
}

func (x *ScoreBreakdown) GetSharedVictory() bool {
	if x != nil {
		return x.SharedVictory
	}
	return false
}

type GameState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MapId             string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	MapVersion        int32                  `protobuf:"varint,2,opt,name=map_version,json=mapVersion,proto3" json:"map_version,omitempty"`
	Phase             Phase                  `protobuf:"varint,3,opt,name=phase,proto3,enum=bgex.ttr.v1.Phase" json:"phase,omitempty"`
	Players           []*PlayerState         `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	CurrentSeat       int32                  `protobuf:"varint,5,opt,name=current_seat,json=currentSeat,proto3" json:"current_seat,omitempty"`
	DrawPile          []int32                `protobuf:"varint,6,rep,packed,name=draw_pile,json=drawPile,proto3" json:"draw_pile,omitempty"`                                                                                 // Color values, draw from front (secret)
	DiscardPile       []int32                `protobuf:"varint,7,rep,packed,name=discard_pile,json=discardPile,proto3" json:"discard_pile,omitempty"`                                                                        // (secret ordering)
	FaceUp            []int32                `protobuf:"varint,8,rep,packed,name=face_up,json=faceUp,proto3" json:"face_up,omitempty"`                                                                                       // exactly 5 unless exhausted (§14)
	TicketDeck        []int32                `protobuf:"varint,9,rep,packed,name=ticket_deck,json=ticketDeck,proto3" json:"ticket_deck,omitempty"`                                                                           // ticket ids, draw front, reject to back
	RouteOwner        map[int32]int32        `protobuf:"bytes,10,rep,name=route_owner,json=routeOwner,proto3" json:"route_owner,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`      // route_id -> seat_index
	ClosedRoutes      []int32                `protobuf:"varint,11,rep,packed,name=closed_routes,json=closedRoutes,proto3" json:"closed_routes,omitempty"`                                                                    // §8.5 2–3p sibling closure
	StationOwner      map[string]int32       `protobuf:"bytes,12,rep,name=station_owner,json=stationOwner,proto3" json:"station_owner,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // city id -> seat_index
	FinalTurnsLeft    int32                  `protobuf:"varint,13,opt,name=final_turns_left,json=finalTurnsLeft,proto3" json:"final_turns_left,omitempty"`                                                                   // -1 until triggered (§11)
	Draw              *DrawProgress          `protobuf:"bytes,14,opt,name=draw,proto3" json:"draw,omitempty"`
	PendingTunnel     *PendingTunnel         `protobuf:"bytes,15,opt,name=pending_tunnel,json=pendingTunnel,proto3" json:"pending_tunnel,omitempty"`
	PendingTicketDraw *PendingTicketDraw     `protobuf:"bytes,16,opt,name=pending_ticket_draw,json=pendingTicketDraw,proto3" json:"pending_ticket_draw,omitempty"`
	Results           []*ScoreBreakdown      `protobuf:"bytes,17,rep,name=results,proto3" json:"results,omitempty"` // populated in PHASE_FINISHED
	Seq               int64                  `protobuf:"varint,18,opt,name=seq,proto3" json:"seq,omitempty"`        // monotonic action counter
	TurnNo            int32                  `protobuf:"varint,19,opt,name=turn_no,json=turnNo,proto3" json:"turn_no,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_internal_games_ttr_pb_ttr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_games_ttr_pb_ttr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_internal_games_ttr_pb_ttr_proto_rawDescGZIP(), []int{5}
}

func (x *GameState) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *GameState) GetMapVersion() int32 {
	if x != nil {
		return x.MapVersion
	}
	return 0
}

func (x *GameState) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *GameState) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameState) GetCurrentSeat() int32 {
	if x != nil {
		return x.CurrentSeat
	}
	return 0
}

func (x *GameState) GetDrawPile() []int32 {
	if x != nil {
		return x.DrawPile
	}
	return nil
}

func (x *GameState) GetDiscardPile() []int32 {
	if x != nil {
		return x.DiscardPile
	}
	return nil
}

func (x *GameState) GetFaceUp() []int32 {
	if x != nil {
		return x.FaceUp
	}
	return nil
}

func (x *GameState) GetTicketDeck() []int32 {
	if x != nil {
		return x.TicketDeck
	}
	return nil
}

func (x *GameState) GetRouteOwner() map[int32]int32 {
	if x != nil {
		return x.RouteOwner
	}
	return nil
}

func (x *GameState) GetClosedRoutes() []int32 {
	if x != nil {
		return x.ClosedRoutes
	}
	return nil
}

func (x *GameState) GetStationOwner() map[string]int32 {
	if x != nil {
		return x.StationOwner
	}
	return nil
}

func (x *GameState) GetFinalTurnsLeft() int32 {
	if x != nil {
		return x.FinalTurnsLeft
	}
	return 0
}

func (x *GameState) GetDraw() *DrawProgress {
	if x != nil {
		return x.Draw
	}
	return nil
}

func (x *GameState) GetPendingTunnel() *PendingTunnel {
	if x != nil {
		return x.PendingTunnel
	}
	return nil
}

func (x *GameState) GetPendingTicketDraw() *PendingTicketDraw {
	if x != nil {
		return x.PendingTicketDraw
	}
	return nil
}

func (x *GameState) GetResults() []*ScoreBreakdown {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GameState) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GameState) GetTurnNo() int32 {
	if x != nil {
		return x.TurnNo
	}
	return 0
}

var File_internal_games_ttr_pb_ttr_proto protoreflect.FileDescriptor

const file_internal_games_ttr_pb_ttr_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/games/ttr/pb/ttr.proto\x12\vbgex.ttr.v1\"\xf8\x03\n" +
	"\vPlayerState\x12\x1d\n" +
	"\n" +
	"seat_index\x18\x01 \x01(\x05R\tseatIndex\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x126\n" +
	"\x04hand\x18\x03 \x03(\v2\".bgex.ttr.v1.PlayerState.HandEntryR\x04hand\x12\x1d\n" +
	"\n" +
	"ticket_ids\x18\x04 \x03(\x05R\tticketIds\x12\x1f\n" +
	"\vtrains_left\x18\x05 \x01(\x05R\n" +
	"trainsLeft\x12#\n" +
	"\rstations_left\x18\x06 \x01(\x05R\fstationsLeft\x12\x1f\n" +
	"\vroute_score\x18\a \x01(\x05R\n" +
	"routeScore\x12*\n" +
	"\x11claimed_route_ids\x18\b \x03(\x05R\x0fclaimedRouteIds\x12%\n" +
	"\x0estation_cities\x18\t \x03(\tR\rstationCities\x12\x1a\n" +
	"\bresigned\x18\n" +
	" \x01(\bR\bresigned\x12,\n" +
	"\x12setup_ticket_offer\x18\v \x03(\x05R\x10setupTicketOffer\x12\x1d\n" +
	"\n" +
	"setup_done\x18\f \x01(\bR\tsetupDone\x1a7\n" +
	"\tHandEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xad\x02\n" +
	"\rPendingTunnel\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\x05R\arouteId\x12N\n" +
	"\fbase_payment\x18\x02 \x03(\v2+.bgex.ttr.v1.PendingTunnel.BasePaymentEntryR\vbasePayment\x127\n" +
	"\rpayment_color\x18\x03 \x01(\x0e2\x12.bgex.ttr.v1.ColorR\fpaymentColor\x12\x1a\n" +
	"\brevealed\x18\x04 \x03(\x05R\brevealed\x12\x1c\n" +
	"\tsurcharge\x18\x05 \x01(\x05R\tsurcharge\x1a>\n" +
	"\x10BasePaymentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"A\n" +
	"\x11PendingTicketDraw\x12,\n" +
	"\x12offered_ticket_ids\x18\x01 \x03(\x05R\x10offeredTicketIds\"^\n" +
	"\fDrawProgress\x12\x1f\n" +
	"\vcards_taken\x18\x01 \x01(\x05R\n" +
	"cardsTaken\x12-\n" +
	"\x13face_up_loco_locked\x18\x02 \x01(\bR\x10faceUpLocoLocked\"\x8f\x05\n" +
	"\x0eScoreBreakdown\x12\x1d\n" +
	"\n" +
	"seat_index\x18\x01 \x01(\x05R\tseatIndex\x12!\n" +
	"\froute_points\x18\x02 \x01(\x05R\vroutePoints\x128\n" +
	"\x18tickets_completed_points\x18\x03 \x01(\x05R\x16ticketsCompletedPoints\x122\n" +
	"\x15tickets_missed_points\x18\x04 \x01(\x05R\x13ticketsMissedPoints\x12#\n" +
	"\rstation_bonus\x18\x05 \x01(\x05R\fstationBonus\x12,\n" +
	"\x12longest_path_bonus\x18\x06 \x01(\x05R\x10longestPathBonus\x12.\n" +
	"\x13longest_path_length\x18\a \x01(\x05R\x11longestPathLength\x12\x14\n" +
	"\x05total\x18\b \x01(\x05R\x05total\x12\x12\n" +
	"\x04rank\x18\t \x01(\x05R\x04rank\x120\n" +
	"\x14completed_ticket_ids\x18\n" +
	" \x03(\x05R\x12completedTicketIds\x12*\n" +
	"\x11missed_ticket_ids\x18\v \x03(\x05R\x0fmissedTicketIds\x12X\n" +
	"\x0fborrowed_routes\x18\f \x03(\v2/.bgex.ttr.v1.ScoreBreakdown.BorrowedRoutesEntryR\x0eborrowedRoutes\x12%\n" +
	"\x0eshared_victory\x18\r \x01(\bR\rsharedVictory\x1aA\n" +
	"\x13BorrowedRoutesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xc9\a\n" +
	"\tGameState\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\x1f\n" +
	"\vmap_version\x18\x02 \x01(\x05R\n" +
	"mapVersion\x12(\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x12.bgex.ttr.v1.PhaseR\x05phase\x122\n" +
	"\aplayers\x18\x04 \x03(\v2\x18.bgex.ttr.v1.PlayerStateR\aplayers\x12!\n" +
	"\fcurrent_seat\x18\x05 \x01(\x05R\vcurrentSeat\x12\x1b\n" +
	"\tdraw_pile\x18\x06 \x03(\x05R\bdrawPile\x12!\n" +
	"\fdiscard_pile\x18\a \x03(\x05R\vdiscardPile\x12\x17\n" +
	"\aface_up\x18\b \x03(\x05R\x06faceUp\x12\x1f\n" +
	"\vticket_deck\x18\t \x03(\x05R\n" +
	"ticketDeck\x12G\n" +
	"\vroute_owner\x18\n" +
	" \x03(\v2&.bgex.ttr.v1.GameState.RouteOwnerEntryR\n" +
	"routeOwner\x12#\n" +
	"\rclosed_routes\x18\v \x03(\x05R\fclosedRoutes\x12M\n" +
	"\rstation_owner\x18\f \x03(\v2(.bgex.ttr.v1.GameState.StationOwnerEntryR\fstationOwner\x12(\n" +
	"\x10final_turns_left\x18\r \x01(\x05R\x0efinalTurnsLeft\x12-\n" +
	"\x04draw\x18\x0e \x01(\v2\x19.bgex.ttr.v1.DrawProgressR\x04draw\x12A\n" +
	"\x0epending_tunnel\x18\x0f \x01(\v2\x1a.bgex.ttr.v1.PendingTunnelR\rpendingTunnel\x12N\n" +
	"\x13pending_ticket_draw\x18\x10 \x01(\v2\x1e.bgex.ttr.v1.PendingTicketDrawR\x11pendingTicketDraw\x125\n" +
	"\aresults\x18\x11 \x03(\v2\x1b.bgex.ttr.v1.ScoreBreakdownR\aresults\x12\x10\n" +
	"\x03seq\x18\x12 \x01(\x03R\x03seq\x12\x17\n" +
	"\aturn_no\x18\x13 \x01(\x05R\x06turnNo\x1a=\n" +
	"\x0fRouteOwnerEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a?\n" +
	"\x11StationOwnerEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01*\xc6\x01\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCOLOR_PURPLE\x10\x01\x12\x0e\n" +
	"\n" +
	"COLOR_BLUE\x10\x02\x12\x10\n" +
	"\fCOLOR_ORANGE\x10\x03\x12\x0f\n" +
	"\vCOLOR_WHITE\x10\x04\x12\x0f\n" +
	"\vCOLOR_GREEN\x10\x05\x12\x10\n" +
	"\fCOLOR_YELLOW\x10\x06\x12\x0f\n" +
	"\vCOLOR_BLACK\x10\a\x12\r\n" +
	"\tCOLOR_RED\x10\b\x12\x0e\n" +
	"\n" +
	"COLOR_GRAY\x10\t\x12\x0e\n" +
	"\n" +
	"COLOR_LOCO\x10\n" +
	"*\xcb\x01\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PHASE_SETUP_TICKETS\x10\x01\x12\x10\n" +
	"\fPHASE_NORMAL\x10\x02\x12\x1e\n" +
	"\x1aPHASE_AWAITING_SECOND_DRAW\x10\x03\x12\x19\n" +
	"\x15PHASE_AWAITING_TUNNEL\x10\x04\x12\x1e\n" +
	"\x1aPHASE_AWAITING_TICKET_KEEP\x10\x05\x12\x11\n" +
	"\rPHASE_SCORING\x10\x06\x12\x12\n" +
	"\x0ePHASE_FINISHED\x10\aB@Z>github.com/serediukit/bgex-backend/internal/games/ttr/pb;ttrpbb\x06proto3"

var (
	file_internal_games_ttr_pb_ttr_proto_rawDescOnce sync.Once
	file_internal_games_ttr_pb_ttr_proto_rawDescData []byte
)

func file_internal_games_ttr_pb_ttr_proto_rawDescGZIP() []byte {
	file_internal_games_ttr_pb_ttr_proto_rawDescOnce.Do(func() {
		file_internal_games_ttr_pb_ttr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_games_ttr_pb_ttr_proto_rawDesc), len(file_internal_games_ttr_pb_ttr_proto_rawDesc)))
	})
	return file_internal_games_ttr_pb_ttr_proto_rawDescData
}

var file_internal_games_ttr_pb_ttr_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_games_ttr_pb_ttr_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_games_ttr_pb_ttr_proto_goTypes = []any{
	(Color)(0),                // 0: bgex.ttr.v1.Color
	(Phase)(0),                // 1: bgex.ttr.v1.Phase
	(*PlayerState)(nil),       // 2: bgex.ttr.v1.PlayerState
	(*PendingTunnel)(nil),     // 3: bgex.ttr.v1.PendingTunnel
	(*PendingTicketDraw)(nil), // 4: bgex.ttr.v1.PendingTicketDraw
	(*DrawProgress)(nil),      // 5: bgex.ttr.v1.DrawProgress
	(*ScoreBreakdown)(nil),    // 6: bgex.ttr.v1.ScoreBreakdown
	(*GameState)(nil),         // 7: bgex.ttr.v1.GameState
	nil,                       // 8: bgex.ttr.v1.PlayerState.HandEntry
	nil,                       // 9: bgex.ttr.v1.PendingTunnel.BasePaymentEntry
	nil,                       // 10: bgex.ttr.v1.ScoreBreakdown.BorrowedRoutesEntry
	nil,                       // 11: bgex.ttr.v1.GameState.RouteOwnerEntry
	nil,                       // 12: bgex.ttr.v1.GameState.StationOwnerEntry
}
var file_internal_games_ttr_pb_ttr_proto_depIdxs = []int32{
	8,  // 0: bgex.ttr.v1.PlayerState.hand:type_name -> bgex.ttr.v1.PlayerState.HandEntry
	9,  // 1: bgex.ttr.v1.PendingTunnel.base_payment:type_name -> bgex.ttr.v1.PendingTunnel.BasePaymentEntry
	0,  // 2: bgex.ttr.v1.PendingTunnel.payment_color:type_name -> bgex.ttr.v1.Color
	10, // 3: bgex.ttr.v1.ScoreBreakdown.borrowed_routes:type_name -> bgex.ttr.v1.ScoreBreakdown.BorrowedRoutesEntry
	1,  // 4: bgex.ttr.v1.GameState.phase:type_name -> bgex.ttr.v1.Phase
	2,  // 5: bgex.ttr.v1.GameState.players:type_name -> bgex.ttr.v1.PlayerState
	11, // 6: bgex.ttr.v1.GameState.route_owner:type_name -> bgex.ttr.v1.GameState.RouteOwnerEntry
	12, // 7: bgex.ttr.v1.GameState.station_owner:type_name -> bgex.ttr.v1.GameState.StationOwnerEntry
	5,  // 8: bgex.ttr.v1.GameState.draw:type_name -> bgex.ttr.v1.DrawProgress
	3,  // 9: bgex.ttr.v1.GameState.pending_tunnel:type_name -> bgex.ttr.v1.PendingTunnel
	4,  // 10: bgex.ttr.v1.GameState.pending_ticket_draw:type_name -> bgex.ttr.v1.PendingTicketDraw
	6,  // 11: bgex.ttr.v1.GameState.results:type_name -> bgex.ttr.v1.ScoreBreakdown
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_internal_games_ttr_pb_ttr_proto_init() }
func file_internal_games_ttr_pb_ttr_proto_init() {
	if File_internal_games_ttr_pb_ttr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_games_ttr_pb_ttr_proto_rawDesc), len(file_internal_games_ttr_pb_ttr_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_games_ttr_pb_ttr_proto_goTypes,
		DependencyIndexes: file_internal_games_ttr_pb_ttr_proto_depIdxs,
		EnumInfos:         file_internal_games_ttr_pb_ttr_proto_enumTypes,
		MessageInfos:      file_internal_games_ttr_pb_ttr_proto_msgTypes,
	}.Build()
	File_internal_games_ttr_pb_ttr_proto = out.File
	file_internal_games_ttr_pb_ttr_proto_goTypes = nil
	file_internal_games_ttr_pb_ttr_proto_depIdxs = nil
}
